### PR TITLE
Add incremental training for GMM inspired by Incremental Learning of …

### PR DESCRIPTION
**Pull request by graiola**
…Temporally-Coherent Gaussian Mixture Models, Arandjelovic and Cipolla.

### CODE REVIEW

**Comment by stulp** [comment]
Hi Gennaro,

The build failed, see the travis output (doesn't compile under clang). Not so clear to me what the problem is there...

Also, the constructor for ModelParametersGMR seems not to be backward compatible, due to a new parameter n_observations that was added before n_input_dims. If someone was previously calling

ModelParametersGMR(priors,means,covars,2)

the 2 would previously refer to n_input_dims. With the new constructor, n_input_dims would be set to the default 1, and n_observations would be set to 2. This is not the desired behavior for this previous call. The desired behavior would be n_input_dims=2, n_observations=default (0)

The best solution would be to make two separate constructors, one with, and one without the n_input_dims parameters. 
ModelParametersGMR(n_observations,priors,means,covars,n_input_dims=1)
ModelParametersGMR(priors,means,covars,n_input_dims=1) // sets n_observations=0 in constructor

Having n_observations at the front is not very pretty, but it needs to be this way otherwise the compiler gets confused between the two constructors due to the default for n_input_dims. 

That would make it backwards compatible.

**Comment by graiola** [comment]
I don't understand why travis refuses to compile it with clang. I tried to compile the code with clang on my machine and it worked just fine.
Anyway, the new pr should address the backward compatibility problem.
What do you think?

**Comment by stulp** [comment]
Yes, backwards compatibility is now good. Thanks for fixing it.

As to the clang problem, I just pushed a change in master in which I only added a space to a file. 
https://github.com/stulp/dmpbbo/commit/0a6cded3f5a8704f5c4b6153e6608d184f9440ad
Before the space it compiled
https://travis-ci.org/stulp/dmpbbo/builds/189797482
but now, after adding a space, it now longer compiles with clang in Travis! 
https://travis-ci.org/stulp/dmpbbo/builds/219814829
So in this case I would blame clang or travis (probably LLVM, when looking at the error message), and not the code: a space shouldn't make too much of a difference, right? ;-)

The only thing that I don't understand is why you deleted the commented out Matlab script generation hack I sometimes use for debugging. I will put it back in later.

**Comment by stulp** [comment]
Sorry, I do understand why you deleted the Matlab script generation now. You removed it from expectationMaximizationIncremental (where it doesn"t make sense). It is still there in expectationMaximization. 

Now dmpbbo has a successful Travis build again:
https://travis-ci.org/stulp/dmpbbo/builds/219821866
(because I disabled clang ;-)

**Comment by graiola** [comment]
Yes I removed the matlab code from the incremental functions (to not duplicate it ;-) 
In the future I will try to upload a demo for the incremental training.

Cheers!

**Pull request merged**
